feature/setup_environment
Kevin-Shen-and-Cipher/course-forum-auth-service pull request #1
Opened 2023-04-25 16:12 UTC by kevemwu

2023-04-27 18:15 UTC, kevemwu commented
正式的環境建立

2023-04-28 01:29 UTC, Kevin-MoonNight commented on compose.yaml
> +      - '8000:8000'
要改成5000

2023-04-28 01:30 UTC, Kevin-MoonNight commented on app/main.py
> +    app.run(debug=True, host='0.0.0.0', port=8888)
改成5000

2023-04-28 01:30 UTC, Kevin-MoonNight requested changes
port部分不統一

2023-04-28 11:10 UTC, Kevin-MoonNight approved these changes

2023-04-28 11:11 UTC, merged